import tkinter as tk
MAX = 0
MIN = 1
WHITE = 'W'
BLACK = 'B'
OUTSIDE = -1
ROW_COL_LENGTH = 3
SMALL = 1
MEDIUM = 2
LARGE = 3
NONE = -1
COLORS = [WHITE, BLACK]
SIZES = [SMALL, MEDIUM, LARGE]
STACKS_NUM = 2
LARGE_STACK_W = 73
LARGE_STACK_H = 4
MEDIUM_STACK_W = 5
MEDIUM_STACK_H = 2